### ISSUE TITLE
Decide On Science Plots/Data Storage

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/StationaryLidar#1]
**NEED** to decide on 
* the *.mat data format/structures (what to call Rapplied and metadata in coreg mat)
* What to call ICP data.  baseline scan and _? scan (source, data, raw, compared)?
* the folder structures
* which *science* plots we're making
* what images we're saving
* How to handle **longer frequency** data analysis... Plot previous 10 profiles, etc.
* How to handle clipping region scans, save rxp data with a unique id in the filename?
* Still ok with method for baseline clipping region?

:octocat: :+1: 

@KateBrodie @atdyer @njspore

**Comment by KateBrodie** [comment]
Some thoughts from an initial convo between Richie & Kate.

   - popsop2rot - pop-up windows/gui for user input
   - *coreg.mat file will have:
      - current "rotdata" structure
      - current "datum" structure
      - current "coredat" structure - with new name?
      - note: maybe name *coreg.mat with filename of first file in folder
      structure
   - "raw" data compared to "baseline" data
   - folder structure TBD
   - Kate will make a list of plots/science ideas that we might not know
   how to visualize yet
   - Save everything!
   - put these in the main loop
   - need to figure out naming "*line.rxp", "*frame.rxp", "*control.rxp"
   - not a square region? ideas on how to do this? also, should improve
   manual typing of region bounding boxes?
   - science plot functions can take in a .rxp and rotation matrix OR ptdat
   structure

**Comment by hokiespurs** [comment]
Issue is outdated, and had too many specific questions.  

- popsop2rot- implemented
- coreg.mat file structure is implemented
- raw vs baseline naming is implemented
- folder structure is in the wiki
- Which plots has been moved to issue #26
- Parts to save is still TBD, but definitely not all raw data
- longer frequency plots are a separate function from the other plots
- naming of files is in the wiki
- moved to a new issue #27
- science plot functions are more modular than this idea
